name: Python application

on: 
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: 3.8
  WORKING_DIR: ./api

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIR }}    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        # python -m pip install --upgrade pip
        pip install flake8 black
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Format with black
      run: |
        # check if the code format is in compliance with black
        black . --check

    - name: Test with pytest
      run: |
        pytest
