name: Docker CI/CD

on:
  push:
    branches:
      - 'muz/add-cd-pipeline'

env:
  WORKING_DIR: ./api

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIR }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_PUSH_TOKEN }} -p ${{ secrets.DOCKERHUB_PUSH_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t muzammil360/ml-kubernetes/api:latest .
          docker push muzammil360/ml-kubernetes/api:latest
